# SPDX-FileCopyrightText: 2024 ThysTips
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "thystips.cloudstack"
SPDX-PackageSupplier = "ThysTips <contact@thystips.net>"
SPDX-PackageDownloadLocation = "https://github.com/thystips/ansible-collection-cloudstack"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "roles/**/tests/inventory"
precedence = "override"
SPDX-FileCopyrightText = "2024 ThysTips <contact@thystips.net>"
SPDX-License-Identifier = "CC0-1.0"
