- name: Templating Netplan Configuration
  ansible.builtin.template:
    src: "netplan.yaml.j2"
    dest: "/etc/netplan/50-cloudstack.yaml"
    mode: "0644"
  when: network_config_provider == "netplan" and (network_netplan_config is defined and network_netplan_config | length > 0)
  notify: Apply Netplan Configuration
